id: A1261234F
base_file: f44CF.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:26:49.515810
  last_modified_at: 2022-05-30 18:26:49.515815
