id: A1261234F
base_file: f2E0A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:26:49.514059
  last_modified_at: 2022-05-30 18:26:49.514066
