id: A1261234F
base_file: fC468.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:26:49.522388
  last_modified_at: 2022-05-30 18:26:49.522391
