id: A1261234F
base_file: f75A3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:26:49.519204
  last_modified_at: 2022-05-30 18:26:49.519211
