id: A1261234F
base_file: fD0AB.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:26:49.533682
  last_modified_at: 2022-05-30 18:26:49.533688
