id: A1261234F
base_file: f0A38.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:26:49.509280
  last_modified_at: 2022-05-30 18:26:49.509286
